NO.39授業レビューの参照
gsdev9/learn-programming pull request #18
Opened 2018-05-03 09:14 UTC by huton338

https://trello.com/c/C2oskKi8/39-%E6%8E%88%E6%A5%AD%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%81%AE%E5%8F%82%E7%85%A7

ユーザー紹介文カラム追加に伴う回収も同時実装。

2018-05-04 07:31 UTC, arapiku requested changes

2018-05-04 07:31 UTC, arapiku commented on app/controllers/AccountController.java
> +import services.UserService;
[IMO] 超今更やけどimport文何件以上で「*」に集約されるか統一した方がいいかもしれんな。

2018-05-04 07:31 UTC, arapiku commented on app/controllers/AccountController.java
> +        User user = userService.findById(userId);
nullチェックいるかも

2018-05-04 07:31 UTC, arapiku commented on conf/routes
>  POST        /userupdate                         controllers.AccountController.UserUpdate
[IMO]`/userdetail` よりかは
`/profile` あるいは `/profile/me`
`/profile/:id`
`/profile/update`
とかにしたほうがわかりやすい気がした。

2018-05-05 02:13 UTC, huton338 commented on app/controllers/AccountController.java
> +import services.UserService;
importが多くなっても明示的にどの部品を呼び出してるか明示的に示した方がいいと思うから「*」で集約しなくてもいいと思うな。
その方が意図しないものを呼び出すこともないし。

2018-05-05 02:22 UTC, huton338 commented on conf/routes
>  POST        /userupdate                         controllers.AccountController.UserUpdate
修正済み。

2018-05-05 02:22 UTC, huton338 commented on app/controllers/AccountController.java
> +        User user = userService.findById(userId);
nullチェック入れました。

2018-05-05 02:36 UTC, arapiku commented on app/controllers/AccountController.java
> +import services.UserService;
> importが多くなっても明示的にどの部品を呼び出してるか明示的に示した方がいいと思う
というのは宗教論争の範疇なので、僕はどっちでもよくて今後統一できれば良いと思いました。

2018-05-05 02:36 UTC, arapiku approved these changes

2018-05-05 02:44 UTC, merged